allowBuilds:
  esbuild: true
overrides:
  esbuild: 0.28.2
  fumadocs-core: 16.14.5
  fumadocs-mdx: 15.3.0
minimumReleaseAgeExclude:
  - '@vercel/geistdocs@1.22.0'
patchedDependencies:
  fumadocs-ui@16.2.2: patches/fumadocs-ui@16.2.2.patch
